SELECT
    CM.ROW_ID ID_CAMBIO,
    CM.X_UNE_OFERTA_ID ID_OFERTA,
    ORDEN.ORDER_NUM ID_PEDIDO,
    ORDEN.STATUS_CD EST_PEDIDO,
    OI.ROW_ID ID_ITEM,
    OI.PAR_ORDER_ITEM_ID ID_ITEM_PADRE,
    OI.ROOT_ORDER_ITEM_ID ID_ITEM_ROOT,
    SPI.NAME PRODUCTO,
    OIX.X_UNE_ID_LEGADO LEGADO,
    OI.X_EVE_INTEG_ID ID_SERVICIO,
    OI.ACTION_CD ACCION,
    OIX.ATTRIB_01 USO,
    OIX.ATTRIB_41 TECNOLOGIA,
    OI.STATUS_CD ESTADO_ITEM,
    OIX.X_EVE_PROVISIONABLE_FLAG APRO,
    OIX.X_EVE_RFS_RECIVED RFS,
    OIX.X_EVE_BILLING_FLAG FACT,
    OIX.X_EVE_RFB_RECIVED RFB,
    OIX.X_EVE_EST_FACTU ESTADO_FACTURACION,
    ORG.DUNS_NUM DOCUMENTO,
    ORG.NAME CUENTA_SERVICIO,
    ORGBILL.NAME CUENTA_FACT,
    SPI.PART_NUM N_PIEZA
FROM SIEBEL.CX_UNEBULKQUOTE CM
LEFT JOIN ( SIEBEL.S_ORDER ORDEN
            INNER JOIN (
                    (((SIEBEL.S_ORDER_ITEM OI
                        LEFT JOIN SIEBEL.S_ORG_EXT ORG ON OI.SERV_ACCNT_ID = ORG.PAR_ROW_ID)               
                    INNER JOIN SIEBEL.S_ORDER_ITEM_X OIX ON OI.ROW_ID = OIX.PAR_ROW_ID)
                    LEFT JOIN SIEBEL.S_PROD_INT SPI    ON OI.PROD_ID = SPI.ROW_ID)
                    LEFT JOIN SIEBEL.S_ORG_EXT ORGBILL ON OI.BILL_ACCNT_ID = ORGBILL.PAR_ROW_ID
            )ON ORDEN.ROW_ID = OI.ORDER_ID
)ON CM.X_UNE_OFERTA_ID = ORDEN.QUOTE_ID
WHERE SPI.TYPE IN('Plan comercial', 'Paquete de canales','Producto')
    AND CM.ROW_ID = '1-DR72NTJU' -- ID DEL CAMBIO
    ORDER BY OI.ACTION_CD;
