SELECT
ORG.DUNS_NUM DOCUMENTO,
ORG.NAME CUENTA_SERVICIO,
ORG_BILL.NAME CUENTA_FACT,
CM.ROW_ID ID_CAMBIO,
CM.X_UNE_ID_ACTIVO ID_SERVICIO,
AI.ROW_ID ID_ACTIVO,
AI.PAR_ASSET_ID ID_COMP_PADRE,
AI.ROOT_ASSET_ID ID_COMP_ROOT,
SPI.NAME PRODUCTO,
AI.STATUS_CD ESTADO,
AI.X_UNE_ID_LEGADO LEGADO,
SPI_PROMO.NAME PROMOCION
FROM SIEBEL.CX_UNEBULKQUOTE CM
INNER JOIN SIEBEL.S_ASSET A ON A.X_EVE_INTEG_ID = CM.X_UNE_ID_ACTIVO
INNER JOIN SIEBEL.S_ORG_EXT ORG ON A.SERV_ACCT_ID = ORG.ROW_ID
INNER JOIN SIEBEL.S_ORG_EXT ORG_BILL ON A.BILL_ACCNT_ID = ORG_BILL.ROW_ID 
INNER JOIN(
        SIEBEL.S_ASSET AI INNER JOIN SIEBEL.S_PROD_INT SPI ON AI.PROD_ID = SPI.ROW_ID       
    )ON AI.ROOT_ASSET_ID = A.ROW_ID
LEFT JOIN SIEBEL.S_PROD_INT SPI_PROMO ON A.PROMOTION_ID = SPI_PROMO.ROW_ID
WHERE CM.ROW_ID = '1-DR72NTJU' -- ID DEL CAMBIO
    AND ORG.ACCNT_TYPE_CD='Servicio';
